config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  get 'index' =>  'pages#index'

  get 'forum' => 'pages#forum'

  get 'vie_scolaire' => 'pages#vie_scolaire'

  get 'vie_exscolaire' => 'pages#vie_exscolaire'

  get 'carnet_medical' => 'pages#carnet_medical'

  get 'contactez-moi'  => 'pages#contact', as: :contact

  get 'compte' => 'pages#compte'

  get 'finance_enf' => 'pages#compte'

  namespace :admin do
    resources :personnes
    resources :familles
    resources :blogs

    root to: "personnes#index"
  end

  devise_for :personnes
  resources :personnes
  resources :familles

  root 'pages#index'

end

app/models/personne.rb
class Personne < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :famille
end

app/controllers/admin/personnes_controller.rb
module Admin
  class PersonnesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Personne.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Personne.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
  before_action :set_personne, only: [:show, :edit, :update, :destroy]

  # GET /personnes
  # GET /personnes.json
  def index
    @personnes = Personne.all
  end

  # GET /personnes/1
  # GET /personnes/1.json
  def show
  end

  # GET /personnes/new
  def new
    @personne = Personne.new
  end

  # GET /personnes/1/edit
  def edit
  end

  # POST /personnes
  # POST /personnes.json
  def create
    @personne = Personne.new(personne_params)

    respond_to do |format|
      if @personne.save
        format.html { redirect_to @personne, notice: 'Personne was successfully created.' }
        format.json { render :show, status: :created, location: @personne }
      else
        format.html { render :new }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnes/1
  # PATCH/PUT /personnes/1.json
  def update
    respond_to do |format|
      if @personne.update(personne_params)
        format.html { redirect_to @personne, notice: 'Personne was successfully updated.' }
        format.json { render :show, status: :ok, location: @personne }
      else
        format.html { render :edit }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnes/1
  # DELETE /personnes/1.json
  def destroy
    @personne.destroy
    respond_to do |format|
      format.html { redirect_to personnes_url, notice: 'Personne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personne
      @personne = Personne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personne_params
      params.require(:personne).permit(:nom, :statut, :datedenaissance, :famille_id)
    end
end

app/helpers/personnes_helper.rb
module PersonnesHelper
end

app/views/personnes/_form.html.erb
<%= form_for(@personne) do |f| %>
  <% if @personne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personne.errors.count, "error") %> prohibited this personne from being saved:</h2>

      <ul>
      <% @personne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :statut %><br>
    <%= f.text_field :statut %>
  </div>
  <div class="field">
    <%= f.label :datedenaissance %><br>
    <%= f.date_field :datedenaissance %>
  </div>
  <div class="field">
    <%= f.label :famille_id %><br>
    <%= f.text_field :famille_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personnes/edit.html.erb
<h1>Editing Personne</h1>

<%= render 'form' %>

<%= link_to 'Show', @personne %> |
<%= link_to 'Back', personnes_path %>

app/views/personnes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personnes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Prenom</th>
      <th>Statut</th>
      <th>Date de naissance</th>
      <th>Famille</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnes.each do |personne| %>
      <tr>
        <td><%= personne.prenom %></td>
        <td><%= personne.statut %></td>
        <td><%= personne.datedenaissance %></td>
        <td><%= personne.famille %></td>
        <td><%= link_to 'Afficher', personne %></td>
        <td><%= link_to 'Editer', edit_personne_path(personne) %></td>
        <td><%= link_to 'Effacer', personne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personne', new_personne_path %>

app/views/personnes/new.html.erb
<h1>New Personne</h1>

<%= render 'form' %>

<%= link_to 'Back', personnes_path %>

app/views/personnes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prenom:</strong>
  <%= @personne.nom %>
</p>

<p>
  <strong>Statut:</strong>
  <%= @personne.statut %>
</p>

<p>
  <strong>Date de naissance:</strong>
  <%= @personne.datedenaissance %>
</p>

<p>
  <strong>Famille:</strong>
  <%= @personne.famille %>
</p>

<%= link_to 'Edit', edit_personne_path(@personne) %> |
<%= link_to 'Back', personnes_path %>