config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  get 'index' =>  'pages#index'

  get 'forum' => 'pages#forum'

  get 'vie_scolaire' => 'pages#vie_scolaire'

  get 'vie_exscolaire' => 'pages#vie_exscolaire'

  get 'carnet_medical' => 'pages#carnet_medical'

  get 'contactez-moi'  => 'pages#contact', as: :contact

  get 'compte' => 'pages#compte'

  get 'finance_enf' => 'pages#compte'

  namespace :admin do
    resources :personnes
    resources :familles
    resources :blogs

    root to: "personnes#index"
  end

  devise_for :personnes
  resources :personnes
  resources :familles

  root 'pages#index'

end

app/models/famille.rb
class Famille < ActiveRecord::Base
end

app/controllers/admin/familles_controller.rb
module Admin
  class FamillesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Famille.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Famille.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/familles_controller.rb
class FamillesController < ApplicationController
  before_action :set_famille, only: [:show, :edit, :update, :destroy]

  # GET /familles
  # GET /familles.json
  def index
    @familles = Famille.all
  end

  # GET /familles/1
  # GET /familles/1.json
  def show
  end

  # GET /familles/new
  def new
    @famille = Famille.new
  end

  # GET /familles/1/edit
  def edit
  end

  # POST /familles
  # POST /familles.json
  def create
    @famille = Famille.new(famille_params)

    respond_to do |format|
      if @famille.save
        format.html { redirect_to @famille, notice: 'Famille was successfully created.' }
        format.json { render :show, status: :created, location: @famille }
      else
        format.html { render :new }
        format.json { render json: @famille.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /familles/1
  # PATCH/PUT /familles/1.json
  def update
    respond_to do |format|
      if @famille.update(famille_params)
        format.html { redirect_to @famille, notice: 'Famille was successfully updated.' }
        format.json { render :show, status: :ok, location: @famille }
      else
        format.html { render :edit }
        format.json { render json: @famille.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /familles/1
  # DELETE /familles/1.json
  def destroy
    @famille.destroy
    respond_to do |format|
      format.html { redirect_to familles_url, notice: 'Famille was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_famille
      @famille = Famille.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def famille_params
      params.require(:famille).permit(:nom)
    end
end

app/helpers/familles_helper.rb
module FamillesHelper
end

app/views/familles/_form.html.erb
<%= form_for(@famille) do |f| %>
  <% if @famille.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@famille.errors.count, "error") %> prohibited this famille from being saved:</h2>

      <ul>
      <% @famille.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/familles/edit.html.erb
<h1>Editing Famille</h1>

<%= render 'form' %>

<%= link_to 'Show', @famille %> |
<%= link_to 'Back', familles_path %>

app/views/familles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Familles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @familles.each do |famille| %>
      <tr>
        <td><%= famille.nom %></td>
        <td><%= link_to 'Show', famille %></td>
        <td><%= link_to 'Edit', edit_famille_path(famille) %></td>
        <td><%= link_to 'Destroy', famille, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Famille', new_famille_path %>

app/views/familles/new.html.erb
<h1>New Famille</h1>

<%= render 'form' %>

<%= link_to 'Back', familles_path %>

app/views/familles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @famille.nom %>
</p>

<%= link_to 'Edit', edit_famille_path(@famille) %> |
<%= link_to 'Back', familles_path %>