config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  get 'index' =>  'pages#index'

  get 'forum' => 'pages#forum'

  get 'vie_scolaire' => 'pages#vie_scolaire'

  get 'vie_exscolaire' => 'pages#vie_exscolaire'

  get 'carnet_medical' => 'pages#carnet_medical'

  get 'contactez-moi'  => 'pages#contact', as: :contact

  get 'compte' => 'pages#compte'

  get 'finance_enf' => 'pages#compte'

  namespace :admin do
    resources :personnes
    resources :familles
    resources :blogs

    root to: "personnes#index"
  end

  devise_for :personnes
  resources :personnes
  resources :familles

  root 'pages#index'

end

app/views/layouts/partials/_footer.html.erb
<div class="last_footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
  <p class="text_footer">
    Simplifier les relations entre parents séparés pour veiller au bien-être et au bon développement de l'enfant.
  </p>

      </div>
      <div class="col-md-4">
<p class="text_footer">
  @Copyright 2016
</p>
      </div>
      <div class="col-md-4">
        <p class="text_footer">KIDCO<p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-default">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       
     </div>
     <div class="collapse navbar-collapse" id="myNavbar">
       <ul class="nav navbar-nav navbar-right">
           <% if personne_signed_in? %>
                Logged in as <strong><%= current_personne.email %></strong>.
                <li><%= link_to 'Edit profile', edit_personne_registration_path %></li>
                <li><%= link_to 'Logout', destroy_personne_session_path, method: :delete %></li>
                <% else %>
                <li><%= link_to 'Sign up', new_personne_registration_path %></li>
                <li><%= link_to 'Login', new_personne_session_path %></li>
            <% end %>
       </ul>
     </div>
   </div>
 </nav>

app/views/layouts/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
          <%= link_to image_tag("logo_kidco.png", alt: "Kidco logo", size: '90x85'), root_path %>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                          aria-haspopup="true" aria-expanded="false">Mon quotidien <span class="caret"></span></a>
              <ul class="dropdown-menu">
                      <li><a href="<%= blogs_path %>">Mon blog</a></li>
                      <li><a href="<%= vie_scolaire_path %>">Ma vie scolaire</a></li>
                      <li><a href="<%= vie_exscolaire_path %>">Ma vie extra-scolaire</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="<%= finance_enf_path %>">Mes finances</a></li>
              </ul>
        </li>
        <li><a href="<%= vie_scolaire_path %>">Calendrier</a></li>
        <li><a href="<%= carnet_medical_path %>">Ma santé</a></li>
        <!-- <li><a href="<%= carnet_medical_path %>">Mon carnet de santé</a></li> -->
        <li><a href="<%= compte_path %>">Mes comptes</a></li>
        <li><a href="<%= forum_path %>">Forum</a></li>
        <li><a href="<%= contact_path %>">Contact</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if personne_signed_in? %>
             <li><%= link_to 'Edit profile', edit_personne_registration_path %></li>
             <li><%= link_to 'Logout', destroy_personne_session_path, method: :delete %></li>
             <% else %>
             <li><%= link_to '', new_personne_registration_path, class: "fa fa-pencil-square-o fa-2x", title: "S'inscrire" %></li>
             <li><%= link_to '', new_personne_session_path, class: "fa fa-sign-in fa-2x", title: "Se connecter" %></li>
         <% end %>
    </ul>


            </div>
        </div>
</nav>